---
title: "Titanic_analysis"
author: "Calvin"
date: "11/08/2021"
output: html_document
---

# Goal

The goal of this analysis is to analyze what type of passenger are more
likely to survive base on list of features and build a predictive model
to make prediction.


```{r loading_data}
library(tidyverse)
library(ggplot2)
library("EnvStats")

# read data
original.titanic.train <- read.csv("train.csv")
original.titanic.test <- read.csv("test.csv")

# Make a temporary copy
titanic.train <- original.titanic.train

# Check each variable type and what data looks like
str(titanic.train)


```

```{r cleaning data}

# Convert some variables to proper type

titanic.train$Survived <- factor(titanic.train$Survived, levels = c(1,0),
                                                         labels = c(1,0))
titanic.train$Pclass <- as.factor(titanic.train$Pclass)

# check missing values
colSums(is.na(titanic.train))
colSums(titanic.train== "")

#fill mode value to Embarked

table(titanic.train$Embarked)
subset(titanic.train, Embarked == "")
titanic.train[c(62,830),]$Embarked <- "S"

# Split first letter of "Cabin" 
with_cabin <- subset(titanic.train, Cabin != "")
cabin_vector <- with_cabin$Cabin
str_split(cabin_vector,pattern="",n=2) -> cabin_list
cabin_letterlist <- c()
j <- 1

for (i in cabin_list){
  cabin_letterlist[j] <- i[1]
  j <- j+1
}

with_cabin$Cabin_letter <- cabin_letterlist

# Merge data back to titanic set

merge(titanic.train,with_cabin, all = TRUE) -> titanic.train
```


```{r predict missing age using lm model with other features}

# Use row with non-null Age value to predict the remaining missing Age values

with_age <- subset(titanic.train, !(is.na(Age)) )
no_age <- subset(titanic.train, (is.na(Age)))


# select potential features for predictor

age_predictor <- lm(Age~ Survived + Pclass + Sex + SibSp + Parch + Fare + Embarked, data = with_age)

summary(age_predictor)

# By Backward model selection

# delete Sex

age_predictor <- lm(Age~ Survived + Pclass + SibSp + Parch + Fare + Embarked, data = with_age)

summary(age_predictor)

# delete Parch

age_predictor <- lm(Age~ Survived + Pclass + SibSp  + Fare + Embarked, data = with_age)

summary(age_predictor)

# delete Embarked

age_predictor <- lm(Age~ Survived + Pclass + SibSp  + Fare, data = with_age)

summary(age_predictor)

# All variables are statistically significant, use above model to predict missing age
predicted_age <- predict(age_predictor, newdata = no_age)
no_age$Age <- predicted_age

# Merge and rearrange data
titanic.train <- rbind(no_age,with_age)
titanic.train <- arrange(titanic.train, PassengerId)
```


# Analysis, analyze Survived vs other features

```{r number of Survived, echo=TRUE}

titanic.train %>% group_by(Survived) %>% summarize(count = n()) %>%
  mutate(Proportion = prop.table(count))

titanic.train %>% ggplot(., aes(x=Survived, fill=Survived)) + geom_bar() + 
  labs(title="Number of Survived \n",subtitle ="0 = Not Survived \n1 = Survived")

```


```{r Survived vs Gender, echo=TRUE}

# table count survive by gender

titanic.train %>% group_by(Survived,Sex)  %>%  
  summarize(count = n()) %>% mutate(Proportion_Survived = prop.table(count))

gender_table <- table(titanic.train$Survived,titanic.train$Sex)
male_total <-sum(gender_table[1,2],gender_table[2,2])
female_total <-sum(gender_table[1,1],gender_table[2,1])

# Visualization

titanic.train %>% ggplot(., aes(x=Survived, fill=Sex)) + geom_bar() +
labs(title="Survived vs Gender \n",subtitle ="0 = Not Survived \n1 = Survived")

titanic.train %>% ggplot(., aes(x=Survived, fill=Survived)) + geom_bar() + facet_wrap(~Sex) +
labs(title="Survived vs Gender \n",subtitle ="0 = Not Survived \n1 = Survived")

# chi-square test

chisq.test(titanic.train$Survived, titanic.train$Sex)

# The result p-value = 2.2e-16, we can reject null hypothesis and conclude there's
# association between survived and gender.

# Odd Ratio

gender_OR <- (gender_table[1,1]/gender_table[1,2])/(gender_table[2,1]/gender_table[2,2])

# The odd ratio is 12.35, the odd of female Survived is 12 times than the odd of male Survived.

# Relative Risk

gender_RR <- (gender_table[2,2]/male_total)/(gender_table[2,1]/female_total)

# The risk of being a male is 3.14 times more than being a female.

# Conclusion: 
# Female are much more likely to survived in Titanic scenario.
```

```{r Survived vs pclass and Gender, echo=TRUE}

# Pclass vs Suvive count and proportion of Pclass for two group Survive = 1 , Survive = 0 
titanic.train %>% group_by(Survived, Pclass) %>% summarize(count = n()) %>%   
  mutate(Proportion_Survived = prop.table(count))

# Visualizaiton

titanic.train %>% ggplot(., aes(x=Sex, fill=Survived)) + geom_bar() + facet_wrap(~Pclass) +
  labs(title="Survived vs Pclass and Gender \n",subtitle ="0 = Not Survived \n1 = Survived")

# By observation, pClass seems to have association with Survived. But we also want to take
# gender into account.

# chi-square test with fixed gender, test whethere Pclass associated with Survived

titanic.train %>% filter(Sex == "male") -> titanic.male
chisq.test(x=titanic.male$Survived, y = titanic.male$Pclass)

titanic.train %>% filter(Sex == "female") -> titanic.female
chisq.test(x=titanic.female$Survived, y = titanic.female$Pclass)

# Both test's result reject null hypothesis and we can conclude there's association between
# Pclass and Survived.

# proportion of Gender in each Pclass

titanic.train %>% group_by(Pclass,Sex) %>%
  summarize(count = n()) %>% mutate(Proportion_Pclass = prop.table(count))


```
```{r Survived vs Fare}

# Box-plot visualization

titanic.train %>% ggplot(., aes(x=Survived,y=Fare)) + geom_boxplot()
# It seems like two group have different mean/median, need further analysis
# Also, the data present some outliers that result skewed data.

boxplot(titanic.train$Fare~titanic.train$Survived, xlab="Survived", ylab="Fare")$out
# 71 outlier are present, this is roughly 8% of the data, we cannot simply exclude them.

# We will do Mann-Whitney U test (a non-parametric test for two independent set)
# to see if median difference are significant

titanic.survive1 <- titanic.train %>% filter(Survived == 1) 
titanic.survive0 <- titanic.train %>% filter(Survived == 0)

wilcox.test(titanic.train$Fare~titanic.train$Survived)

# The result of test reject null hypothesis and conclude there's difference in median.

# Additionally, we can take samples from two distribution to see if mean of sample average 
# are different

sample_fare_survive1 <- c()
sample_fare_survive0 <- c()

# Sample from two different group (Survived = 1 or 0)
for (i in 1:100){
   sample_fare_survive1[i] <- mean(sample(titanic.survive1$Fare, size = 100))
   sample_fare_survive0[i] <- mean(sample(titanic.survive0$Fare, size = 100))
}


# By central limit theorem, distribution of sample average is normal, we can use t-test
t.test(sample_fare_survive1,sample_fare_survive0)

# The result reject null hypothesis and conclude the sample average are different between
# two groups, which means Survived are associated with Fare.


# Conclusion:
# Fare are associated with Survived
```

